from collections.abc import Mapping
from pathlib import Path

EXIT_CODE: int

def exit_unless_production_ready() -> bool: ...

class ProductionConfigError(RuntimeError): ...

def is_production(env: Mapping[str, str]) -> bool: ...
def validate_production_config(env: Mapping[str, str], app_root: Path) -> list[str]: ...
def enforce_production_config(env: Mapping[str, str] | None = None, app_root: Path | None = None) -> bool: ...
